-- MySQL Script generated by MySQL Workbench
-- Thu Jan  7 00:07:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET
    @OLD_UNIQUE_CHECKS = @ @UNIQUE_CHECKS,
    UNIQUE_CHECKS = 0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @ @SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;

USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
    `id_categoria` INT NOT NULL AUTO_INCREMENT,
    `nombre_categoria` VARCHAR(45) NULL,
    PRIMARY KEY (`id_categoria`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
    `id_producto` INT NOT NULL AUTO_INCREMENT,
    `nombre_prodcuto` VARCHAR(45) NULL,
    `stok` INT NULL,
    `categorias_id_categoria` INT NOT NULL,
    PRIMARY KEY (`id_producto`),
    INDEX `fk_productos_categorias_idx` (`categorias_id_categoria` ASC) VISIBLE,
    CONSTRAINT `fk_productos_categorias` FOREIGN KEY (`categorias_id_categoria`) REFERENCES `mydb`.`categorias` (`id_categoria`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
    `id_persona` INT NOT NULL,
    `nombre_completo` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id_persona`, `nombre_completo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
    `id_venta` INT NOT NULL AUTO_INCREMENT,
    `fecha` DATETIME NULL,
    `personas_id_persona` INT NOT NULL,
    PRIMARY KEY (`id_venta`, `personas_id_persona`),
    INDEX `fk_ventas_personas1_idx` (`personas_id_persona` ASC) VISIBLE,
    CONSTRAINT `fk_ventas_personas1` FOREIGN KEY (`personas_id_persona`) REFERENCES `mydb`.`personas` (`id_persona`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`productos_has_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos_has_ventas` (
    `productos_id_producto` INT NOT NULL,
    `ventas_id_venta` INT NOT NULL,
    PRIMARY KEY (`productos_id_producto`, `ventas_id_venta`),
    INDEX `fk_productos_has_ventas_ventas1_idx` (`ventas_id_venta` ASC) VISIBLE,
    INDEX `fk_productos_has_ventas_productos1_idx` (`productos_id_producto` ASC) VISIBLE,
    CONSTRAINT `fk_productos_has_ventas_productos1` FOREIGN KEY (`productos_id_producto`) REFERENCES `mydb`.`productos` (`id_producto`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_productos_has_ventas_ventas1` FOREIGN KEY (`ventas_id_venta`) REFERENCES `mydb`.`ventas` (`id_venta`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET
    SQL_MODE = @OLD_SQL_MODE;

SET
    FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET
    UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;